import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { connectToDatabase } from '../util/mongodb'
import Link from 'next/link'
import { useState } from 'react'
import { Props } from './Props'

export async function getServerSideProps() {
  const { client } = await connectToDatabase()
  const projection = { _id: 1, client_information: 1 }
  const unenteredRecords = await client.db('spars_cmhs').collection('clients').find({
    spars_entry: false
  }).project(projection).toArray()
  const serializedRecords = JSON.parse(JSON.stringify(unenteredRecords))
  return {
    props: { serializedRecords }
  }
}

function Home({ serializedRecords }: Props) {
  const [records] = useState(serializedRecords)
  return (
    <div className={styles.container}>
      <Head>
        <title>NOMS SPARS Todo</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Your NOMS SPARS Todo
        </h1>
        {records.length > 0 ?
          <div className={styles.grid}>
            <h1>Below are clients that need to be entered into SPARS</h1>
            <p>{records[0]._id}</p>
            {records.map(record => {
              { console.log(record)} 
              <Link href='/detail/:client_id' as={`/detail/${record._id}`}>
                <div className={styles.card}>
                  {/* <h1>{record.client_information.client_info.name}</h1> */}
                  {/* <h3>{record.client_information.interview_type}</h3> */}
                  {/* <h1>{record.client_information.interviewDate}</h1> */}
                </div>
              </Link>
            })}
          </div>
          :
          <h1>You are all caught up on your SPARS Data Entry</h1>}
      </main>
    </div>
  )
}

export default Home
